Dockerfile
And jre 102, also removed the patch being applied as these fixes are directly in the newer nexus release
=> Updated to nexus 3.0.1-01

docker-compose.yml
Quick lil ditty to allow someone to use docker-compose to run nexus
=> Docker compose file for Nexus Repository Manager 3

README.md
=> Update Persistent Data to use docker volume instead of data container

README.md
Also adding a TOC to mimic the README on our rhel Docker image
=> Update README to add Getting Help section

docker-compose.yml
Making sure this is up to date, in case people are using it.
=> Updating docker-compose to use the new appropriate image name

Dockerfile
Prior release no longer available, url now has a new format.
=> update java download url

Dockerfile, README.md
https://issues.sonatype.org/browse/NEXUS-14196
=> [NEXUS-14196] Expose MaxDirectMemorySize via INSTALL4J_ADD_VM_PARAMS

Dockerfile, README.md
https://issues.sonatype.org/browse/NEXUS-13905
=> [NEXUS-13905] Put java user prefs in work directory

README.md
Update README to include testing, Chef recipe location.
Some polish on the README as a follow up to the Integrations team's work in standardizing our approach to virtual machines and images.
=> Update README to include testing, Chef recipe location.

Dockerfile
Upgrade to Nexus Repository Manager 3.6.1-02.
=> Upgrade to Nexus Repository Manager 3.6.1-02

Jenkinsfile
Allow the docker repository name to be different than the github repository name.
=> INT - Allow docker repository name

Dockerfile
Just updated to the latest revision of nexus.
=> Bumped release to 3.6.2.

Dockerfile
* Update Repository Manager to 3.7.0-04.
* Update Repository Manager Cookbook to release-0.5.20171219-161323.cc1040a.
=> INT - Update Repository Manager to 3.7.0-04

Jenkinsfile
Automate version updates for the nexus-repository-manager and chef-nexus-repository-manager cookbook.
=> INT - Automate Version Update

Jenkinsfile
Current Jenkinsfile uses scm.branch[0].name which gives `*/master` for master and the absolute branch name for feature branches. Use `env.BRANCH_NAME` which gives absolute branch name for all branches.
=> Use ENV for Branch Name

Dockerfile, Dockerfile.rh.centos, Dockerfile.rh.el, Jenkinsfile
(brief, plain english overview of your changes here)
* (your change here)
* (another change here)
* (etc)
(If there are changes to user behavior in general, please make sure to
update the README, as well)
It relates to the following issue #s:
* Fixes #X
=> Update JRE Url from Jenkins test

Jenkinsfile
Adjust CI library to new shared library.
=> CI Pipeline Library

Dockerfile, README.md
Switched the base image to UBI 8 instead of CentOS which resolved the OS level vulnerabilities.
=> NEXUS-20366 - Use UBI8 instead of CentOS

Dockerfile, Dockerfile.rh.centos, Dockerfile.rh.el
=> INT Pull in PR #113 update labels

Dockerfile, Dockerfile.rh.centos, Dockerfile.rh.el, Dockerfile.rh.ubi, README.md
Update heap defaults to match https://help.sonatype.com/repomanager3/installation/system-requirements#SystemRequirements-ExampleMaximumMemoryConfigurations
=> Update heap defaults

Jenkinsfile
use jenkins-shared library explicitly
=> Use jenkins shared

Jenkinsfile
https://issues.sonatype.org/browse/NEXUS-26281
=> [NEXUS-26281] docker push —all-tags

Jenkinsfile, Jenkinsfile-Release
enable IQ evaluation on all builds.
JIRA: https://issues.sonatype.org/browse/INT-3860
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/docker-nexus3-feature/job/INT-3860-add-iq-eval/
=> INT-3860 add iq eval

README.md
Adding links directly to the dockerfile helps visibility within dockerhub.
=> Add dockerfile links to readme

Jenkinsfile.rh, build_red_hat_image.sh
build and validate for red hat.
JIRA: https://issues.sonatype.org/browse/INT-6885
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/Red%20Hat/job/docker-nexus-repository-red-hat-release/2/
=> INT-6885 red hat build

Dockerfile.rh.centos, Dockerfile.rh.el, Dockerfile.rh.ubi, rh-docker/help.1, rh-docker/help.md, rh-docker/licenses/LICENSE, rh-docker/uid_entrypoint.sh, rh-docker/uid_template.sh
=> NEXUS-34767 - Remove chef from secondary Dockerfiles

Jenkinsfile.rh, build_red_hat_image.sh
switch to new red hat registry and credentials for building the red hat certified image.
JIRA: https://issues.sonatype.org/browse/INT-7341
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/Red%20Hat/job/release-test/1/
=> INT-7341 new red hat registries

validate-expectations-results.xml
See https://github.com/sonatype/jenkins-shared/pull/281
=> BNR-1116_cleanupExpectations

Jenkinsfile-Internal-Release
JIRA: https://sonatype.atlassian.net/browse/NEXUS-40270
=> NEXUS-40270: add job

Jenkinsfile-Internal-Release
=> Nexus-40270: url fix

Jenkinsfile
Change credentialid of Jenkinsfile
=> Change on github credentialid

Dockerfile, Dockerfile.Java11, Dockerfile.java11, Dockerfile.rh.centos, Dockerfile.rh.el, Dockerfile.rh.ubi, Dockerfile.rh.ubi.java11, Jenkinsfile-Internal-Release, Jenkinsfile-Release, Jenkinsfile.rh, build_red_hat_image_for_java11.sh
Ticket: [NEXUS-41468](https://sonatype.atlassian.net/browse/NEXUS-41468) Java 11 - Create Java runtime based docker images
**CI:** 
* [Test Job Java 11](https://jenkins.ci.sonatype.dev/job/nxrm/job/nxrm3/job/Experiments/job/Publish-Docker-Nexus/10/)
* [Test Job Java 8](https://jenkins.ci.sonatype.dev/job/nxrm/job/nxrm3/job/Experiments/job/Publish-Docker-Nexus/11/)
* [Test Release Docker Java 11](https://jenkins.ci.sonatype.dev/job/nxrm/job/nxrm3/job/Experiments/job/Release-Docker-Nexus/4/flowGraphTable/)
**Jenkins UI**
**RSC Docker Java 11**
**RSC Docker Java 8**
[NEXUS-41468]: https://sonatype.atlassian.net/browse/NEXUS-41468?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> NEXUS-41468 Java 11 - Create Java runtime based docker images

Jenkinsfile-Internal-Release
Publish Docker image with Java 8 throws error on CI
=> Fix publish docker image

Jenkinsfile-Release
**Ticket:** [NEXUS-42249](https://sonatype.atlassian.net/browse/NEXUS-42249) Do not publish Docker image for java 11 with latest tag
[NEXUS-42249]: https://sonatype.atlassian.net/browse/NEXUS-42249?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> NEXUS-42249 Do not publish Docker image for java 11 with latest tag

Dockerfile.java17, Dockerfile.rh.ubi.java17, Jenkinsfile-Internal-Release, Jenkinsfile-Release, Jenkinsfile.rh
Ticket: [NEXUS-42436](https://sonatype.atlassian.net/browse/NEXUS-42436) Java 17 - Create Java 17 runtime based docker image
**CI:** [Test Job Java 17](https://jenkins.ci.sonatype.dev/job/nxrm/job/nxrm3/job/Experiments/job/Publish-Docker-Nexus/)
**Jenkins UI**
[NEXUS-42436]: https://sonatype.atlassian.net/browse/NEXUS-42436?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> NEXUS-42436 Java 17 - Create Java 17 runtime based docker image

Dockerfile.rh.ubi
Remove gzip for docker-nexus-repository-redhat-release job
=> Remove gzip

Jenkinsfile.rh
Update preflight version to 1.9.4 for RedHat
=> Update Preflight version

Jenkinsfile-Release
Version is not being included for the java11 and 17 commands
=> Fix version exclusion typo

Dockerfile.java11, Dockerfile.rh.ubi.java11
This reverts commit 9656ce225243c5650037ae108bd0a499cff64b45.
=> Revert "Update Repository Manager to 3.68.1-02."

build_red_hat_image.sh
=> Fix docker tag command

Jenkinsfile-PrismaCloud
This Jenkinsfile creates two PrismaCloud reports, one for the UBI (RedHat) image & one for the docker-nexus3 image
It also publishes both docker image SBOMs similar to NEXUS-42442
[Jenkins Job](https://jenkins.ci.sonatype.dev/job/nxrm/job/nxrm3/job/PrismaCloud%20SBOM/)
=> Nexus 42441 Prisma Cloud

Jenkinsfile-PrismaCloud
Change UBI Link
[NEXUS-42441](https://sonatype.atlassian.net/browse/NEXUS-42441)
[NEXUS-42441]: https://sonatype.atlassian.net/browse/NEXUS-42441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Change UBI Link

Dockerfile.alpine, Jenkinsfile.alpine
This PR:
- Adds the Alpine base image Dockerfile
- Creates a temp Jenkins job to build image and push the result to Sonatype's internal repo
[NEXUS-42431](https://sonatype.atlassian.net/browse/NEXUS-42431)
[NEXUS-42431]: https://sonatype.atlassian.net/browse/NEXUS-42431?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> NEXUS-42431-Alpine

README.md
Added Alpine Description
[NEXUS-42416](https://sonatype.atlassian.net/browse/NEXUS-42416)
[NEXUS-42416]: https://sonatype.atlassian.net/browse/NEXUS-42416?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> NEXUS-42416

Jenkinsfile-Internal-Release, Jenkinsfile-Release
Added new docker tags to have a default tag of sonatype/nexus3:3.xx.Y which uses UBI and Java8
JIRA: https://sonatype.atlassian.net/browse/NEXUS-43520
=> Nexus 43520 docker tags

Jenkinsfile-Internal-Release, Jenkinsfile-Release
- Change Jenkinsfile-Release and Jenkinsfile-Internal-Release to only use Java17
- Change tagging to accomodate this change, new tags are:
3.71.0  (Default tag)
3.71.0-ubi (Default UBI tag)
3.71.0-alpine (Default Alpine tag)
3.71.0-java17-alpine
3.71.0-java17-ubi
Jira: https://sonatype.atlassian.net/browse/NEXUS-43823
=> Nexus 43823 java17

Dockerfile.rh.ubi.java17, Jenkinsfile.rh
remove java versions for redhat dockerfile / jenkinsfile. Now points explicitly at java17
=> Remove java versions

build_red_hat_image.sh
old script specifies java version, this is no longer desired and causes build failures
=> Fix rh script with java version

Jenkinsfile-Release
Trimming problem areas from 3.70.2 release.
=> release: trim problematic phases for 3.72.0 release

README.md
update legal discaimer for commmunity on docker hub
=> NEXUS-45492_update_dockerhub_legal_with_community_eula

Jenkinsfile-Internal-Release-OrientDB, Jenkinsfile-Release-OrientDB
https://sonatype.atlassian.net/browse/NEXUS-45852
Add latest-3.70.x tag for the Orient extended maintenance releases
=> NEXUS-45852: Add latest 3.70.x tag

Jenkinsfile.rh
Update the red hat preflight image used to latest
=> update preflight image to 1.13.0

Dockerfile.rh.ubi.java17
Update the repo version to 3.80.0-06 for red hat ubi
=> update repo version to 3.80.0-06

Dockerfile.alpine.java17, Dockerfile.java17, Dockerfile.rh.ubi.java17
Update Nexus Version for Release
=> Release version 3.81.0-08

Dockerfile.alpine.java17, Dockerfile.java17, Dockerfile.rh.ubi.java17
Update Nexus Version for Release
=> Update version for release 3.82.0
