Dockerfile

This PR rewrites the Dockerfile CMD clause to use the [recommended](https://docs.docker.com/engine/reference/builder/#cmd) 'exec' form instead of the current 'shell' form.
This should make it easier to properly stop the container, as reported in #6.

Dockerfile: CMD use the recommended 'exec' form instead of 'shell' form.

---

README.md
docker-compose.yml

A new image has been setup in the hub for automated builds and it's name is docker-nexus3, updating our docs to reflect usage of that image.

Update image name to docker-nexus3

---

Dockerfile
README.md

Fabdouglas patch 1

---

Dockerfile

Follows best practices from: https://docs.docker.com/engine/reference/builder/#env to reduce number of layers, help with cache invalidation per #18

Modifications to ENV variables to follow best practices

---

Dockerfile

Updated to use 3.1 release and new directory layout

NEXUS-11119 - Nexus 3.1 layout changes

---

Dockerfile

Updated to the latest JRE. Reduced the custom configuration while maintaining the `/nexus-data` volume.

Updated JRE and reduced custom config

---

README.md

Noticed these references to nexus-docker3 tho that is deprecated.

Updating references to the non-deprecated image

---

Dockerfile
README.md

Allow NEXUS_VERSION and NEXUS_DOWNLOAD_URL to be overridden at build time, e.g.
```
docker build -t nexus-custom --build-arg NEXUS_VERSION=3.x.y --build-arg NEXUS_DOWNLOAD_URL=http://.../nexus-3.x.y-unix.tar.gz .
```

Introduce build arguments

---

Dockerfile
README.md

With this change the heap size settings can be overriden as follows:
```
docker run -e INSTALL4J_ADD_VM_PARAMS="-Xms2g -Xmx2g" sonatype/nexus3
```

[NEXUS-12835] Move java memory opts to INSTALL4J_ADD_VM_PARAMS

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTORS.md
LICENSE
README.md

This adds in quite a few of the newer Community "standards" such as:
- Templates for issues and PRs
- Contribution guidelines
- Contributors list
- Updates to README to link to Gitter for more real time help, and contribution guidelines
As well, updates LICENSE to full Apache 2.0 text (allows it to show up as our license on GitHub), and adds in the header to the README, as it was missing

Contribution Updates

---

solo.json.erb

The variable being used for the checksum is not used by the chef download recipe for nexus.

Fixed incorrect checksum property variable for chef recipe

---

Dockerfile

Update Chef template to remove LoadAsOSS override. This override forced Nexus to run as OSS despite the existence of a license.
It relates to the following issue #s:
* INT-406 (Sonatype Internal)

INT-406 Remove LoadAsOSS

---

CONTRIBUTORS.md
Dockerfile
Dockerfile.rh.centos
Dockerfile.rh.el
Jenkinsfile
solo.json.erb

Switch from Oracle JDK to OpenJDK 8.
* Removes code related to Oracle JDK
* Uses OpenJDK 8 as dependency in Chef's recipe
It relates to the following issue #s:
* Resolves [NEXUS-18693](https://issues.sonatype.org/browse/NEXUS-18693)

Switchover to OpenJDK

---

Dockerfile

Lock the version to 14.x to avoid automatically accepting the EULA on behalf of a user.
The omnibus documentation suggests this method for setting the version - https://docs.chef.io/install_omnibus.html
I arbitrarily chose the latest 14.x version listed in the changelog - https://github.com/chef/chef/blob/master/CHANGELOG.md

Specify Chef version

---

Dockerfile
Dockerfile.rh.centos
Dockerfile.rh.el

* Merge MAINTAINER metadata into LABEL to reduce layers for the Centos and RHEL Dockerfiles
* Populate LABEL for the base Dockerfile with metadata found in Centos & RHEL
Closed out #112 which was against a separate branch and replaced with this PR against master branch.

Update metadata for Dockerfile label

---

Dockerfile
Dockerfile.rh.centos
Dockerfile.rh.el
Dockerfile.rh.ubi

cloud-ops email didn't really exist, so switch it to support@sonatype.com.

cloud-ops email -> support

---

Jenkinsfile
ci/TriggerRedHatBuild.groovy

1. allow red hat builds to be skipped in case the service is down
2. retry on failure of service while watching for build to finish.
JIRA: https://issues.sonatype.org/browse/INT-2562

INT-2562 resilience for red hat trigger

---

Dockerfile

To get onto openjdk 8u282 we need to manually deal with java, as 282 is no longer the latest bulid, and the current (292) has a bug that is causing SAML to not function (fix is in 302 which is still in EA)
* Switched to the new 3x-docker chef recipe (which has no java recipe)
* Manually download/install the 8u282 openjdk build
This PR depends on https://github.com/sonatype/chef-nexus-repository-manager/pull/59

NEXUS-27617: Using new chef recipe that doesn't include java management

---

Jenkinsfile

the script to trigger the red hat build service is broken, and will soon be updated. in the meantime, disable it, so it doesn't fail the build for the plain docker image.
JIRA: https://issues.sonatype.org/browse/INT-5543
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/docker-nexus3-feature/job/INT-5543-disable-redhat/

disable red hat trigger until the script is corrected

---

Dockerfile
Dockerfile.rh.centos
Dockerfile.rh.ubi

Java in the main image was pinned at an older version about a 9 months ago for a bug in java (https://issues.sonatype.org/browse/NEXUS-27617, previous PR I'm partially undoing: https://github.com/sonatype/docker-nexus3/pull/129). It was fixed in the 302 build (https://bugs.openjdk.java.net/browse/JDK-8267766), so this can go back to the way it was. I think the `docker-3x` recipe in the chef repo could go away as well, since this is no longer using it.
Also, the chef recipe hasn't been updated in a while. The Red Hat images were left even more out of date since before the pinning of the JVM. I'm finding the Dockerfile.rh.el file for RHEL7 to be unbuildable, since it's saying there's no openjdk 8 candidate available there, so I've not touched that one. I know I only have direct use for the …

Latest Chef Recipes and Latest Java 8

---

Jenkinsfile
Jenkinsfile-Release

We're instating a master snapshot build for docker-nexus3. Jenkinsfile will be the default build that is used for snapshot builds/tests/scans of features and master. Jenkinsfile-Release will be used by the existing docker-nexus3 build in jenkins to do a release. That existing job will not be renamed, but it will be rewired to run Jenkins-Release, which is an unchanged copy of the old Jenkinsfile.
JIRA: https://issues.sonatype.org/browse/INT-3860
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/docker-nexus3-feature/job/INT-3860-snapshot-build/

INT-3860 split the jenkinsfiles for a snapshot and a release build

---

Dockerfile

Removes the usage of Chef from the creation of the image, and switches to `ubi9/ubi-minimal` from `ubi8/ubi` to reduce the amount of cruft in the image.

NEXUS-34767 - Remove chef and switch to ubi8/ubi-minimal

---

Jenkinsfile
Jenkinsfile-Release
Jenkinsfile.rh
README.md

This pull request updates references to the default branch to now use 'main' instead of 'master'.
After it is merge, the default branch has to be changed in the repo, and the following Jenkins configuration must to be point to main branch:
https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/docker-nexus3/configure 
https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/docker-nexus3-feature/configure 
https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/docker-nexus3-master-snapshot/configure

IDay: Update Jenkinsfiles to use new 'main' default branch

---

Dockerfile
Dockerfile.rh.centos
Dockerfile.rh.el
Dockerfile.rh.ubi

* Adds a simple command to remove the memory settings lines from nexus.vmoptions when building the image
It relates to the following issue #s:
* Fixes NEXUS-35218

NEXUS-35218:  memory settings removal from nexus.vmoptions

---

Dockerfile
Dockerfile.rh.centos
Dockerfile.rh.el
Dockerfile.rh.ubi

The NEXUS_CONTEXT environment is not working.
RUN echo "#!/bin/bash" >> ${SONATYPE_DIR}/start-nexus-repository-manager.sh \
&& echo "cd /opt/sonatype/nexus" >> ${SONATYPE_DIR}/start-nexus-repository-manager.sh \
&& echo "exec ./bin/nexus run" >> ${SONATYPE_DIR}/start-nexus-repository-manager.sh \
&& chmod a+x ${SONATYPE_DIR}/start-nexus-repository-manager.sh \
**_&& sed -e '/^nexus-context/ s:$:${NEXUS_CONTEXT}:' -i ${NEXUS_HOME}/etc/nexus-default.properties_**

the env NEXUS_CONTEXT is not working, fix it

---

Jenkinsfile-Release

https://issues.sonatype.org/browse/BNR-1026
Makes image available via internal registries for deployment.

Push image to sonatype internal registries.

---

Jenkinsfile-Release

This job is still on the legacy agent which cannot authenticate to docker-internal.rsc-proxy  We pull the image through before attempting to deploy it anyway so we don't really need to do it here.
https://github.com/sonatype/nxrm-deploy/blob/c11892302ad562ef846bc7c062736281eb1165f9/release/Jenkinsfile.prod#L34

Don't pull image through here, the deployment job does that before deploying

---

Jenkinsfile
Jenkinsfile-Internal-Release
Jenkinsfile-Release

The quiet flag can hide useful output when the build fails.

NEXUS-42789 - Remove quiet flag from builds

---

Jenkinsfile-sbom-release

Ticket: https://sonatype.atlassian.net/browse/NEXUS-43198
CI: https://jenkins.ci.sonatype.dev/job/nxrm/job/nxrm3/job/Docker%20image%20SBOM%20release%20Test/
This PR adds support for any docker tag (ubi and alpine) in SBOM release pipeline.
It relates to the following tickets:
* https://sonatype.atlassian.net/browse/NEXUS-43198
* https://sonatype.atlassian.net/browse/NEXUS-42221

NEXUS-43198: Added support for alpine tags in SBOM release pipeline

---

Dockerfile.alpine.java11
Dockerfile.alpine.java17

Bump openssl to a non vulnerable version.
[NEXUS-43508](https://sonatype.atlassian.net/browse/NEXUS-43508)
[NEXUS-43508]: https://sonatype.atlassian.net/browse/NEXUS-43508?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

NEXUS-43508

---

Jenkinsfile-Release

This removes the input prompt to "Proceed" or "Abort" with the pipeline job.

build: skip the prompt

---

Jenkinsfile.rh

(🧹 Chore)
updating openshift-preflight version on Jenkinsfile.rh
Openshift-preflight version needs to be upgraded for RedHat OpenShift Operator release NXRM 3.72.0
https://sonatype.atlassian.net/browse/NEXUS-43864

updating openshift-preflight version on Jenkinsfile.rh

---

Jenkinsfile.rh

Fixes the jenkins job https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/Red%20Hat/job/docker-nexus-repository-red-hat-release/45/console
```
2024-11-05 07:59:06 GMT  time="2024-11-05T07:59:05Z" level=info msg="preparing results that will be submitted to Red Hat"
2024-11-05 07:59:06 GMT  time="2024-11-05T07:59:06Z" level=error msg=release-url error="invalid preflight version, please download the latest version and re-submit"
2024-11-05 07:59:06 GMT  Error: could not submit to pyxis: could not create test results: status code: 400: body: {"type": "about:blank", "title": "Bad Request", "detail": "Validation error: 'github.com/redhat-openshift-ecosystem/openshift-preflight' version '1.10.0' is not supported. Supported versions are: ['1.10.1', '1.10.2']", "status": 400, …
```

update openshift-preflight to 1.10.2

---

Dockerfile.java17
Dockerfile.rh.ubi.java17

Exporting the internal changes so that the 3.76.0 release images based off of UBI are upgraded to UBI 9.

NEXUS-44919: update to UBI 9 (minimal)

---

Dockerfile.alpine.java17
Dockerfile.java17
Jenkinsfile-Release

Accommodate new assembly shape and update platform targets.

NEXUS-46138: Dockerfile and build changes for 3.78.0 release

---

Dockerfile.java17
Dockerfile.rh.ubi.java17

Docker images often contain UTF-8 encoded filenames within the layers. In order to properly extract them for Firewall for Docker evaluation, we need the system locale to be configured appropriately.

NEXUS-48206: set locale to UTF-8 on UBI based images

---

Jenkinsfile.rh

This pull request updates the version of the `preflight` tool used in the Jenkins pipeline. The change ensures that the pipeline uses the latest release of `preflight`.
Dependency version update:
* Updated the download link in `Jenkinsfile.rh` to use `preflight` version 1.14.1 instead of 1.13.0.

Upgrading preflight to 1.14.1 version.
